[package]
name = "htmlform"
version = "0.1.0"
authors = ["Guido Wesdorp <johnnydebris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
regex = "1"
hex = "0.4"
